INSERT INTO PAIS(NOME) VALUES('Brasil')
INSERT INTO PAIS(NOME) VALUES('Argentina')
INSERT INTO PAIS(NOME) VALUES('Estados Unidos')

INSERT INTO ESTADO(NOME, PAIS_ID) VALUES ('São Paulo', 1)
INSERT INTO ESTADO(NOME, PAIS_ID) VALUES ('Rio de Janeiro', 1)
INSERT INTO ESTADO(NOME, PAIS_ID) VALUES ('New York', 3)

INSERT INTO CATEGORIA(NOME) VALUES ('Desenvolvimento')

INSERT INTO AUTOR (DATA_CADASTRO, DESCRICAO, EMAIL, NOME) VALUES ('2021-01-31 22:02:33.838362', 'O brabo das laranjas', 'aowclaudiao@gmail.com', 'Claudio Clebin')

